// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5auJzoV4_Hcz5bgYMZJ2c2aOIqrgfxiE',
    appId: '1:444020048554:web:00ef722a95e6f77c7746d3',
    messagingSenderId: '444020048554',
    projectId: 'studyhub-a667b',
    authDomain: 'studyhub-a667b.firebaseapp.com',
    storageBucket: 'studyhub-a667b.firebasestorage.app',
    measurementId: 'G-21EWWMDVW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzO6Q1XKVstCgV0NUwyTbx6oygcomEYWU',
    appId: '1:444020048554:android:9d5d94542a07322e7746d3',
    messagingSenderId: '444020048554',
    projectId: 'studyhub-a667b',
    storageBucket: 'studyhub-a667b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzeoIgcNpSOsLdy9kjZkk3XHB3FNVjdXg',
    appId: '1:444020048554:ios:365c34439df3aa087746d3',
    messagingSenderId: '444020048554',
    projectId: 'studyhub-a667b',
    storageBucket: 'studyhub-a667b.firebasestorage.app',
    iosBundleId: 'com.example.studyhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzeoIgcNpSOsLdy9kjZkk3XHB3FNVjdXg',
    appId: '1:444020048554:ios:365c34439df3aa087746d3',
    messagingSenderId: '444020048554',
    projectId: 'studyhub-a667b',
    storageBucket: 'studyhub-a667b.firebasestorage.app',
    iosBundleId: 'com.example.studyhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5auJzoV4_Hcz5bgYMZJ2c2aOIqrgfxiE',
    appId: '1:444020048554:web:7254ba008bb232987746d3',
    messagingSenderId: '444020048554',
    projectId: 'studyhub-a667b',
    authDomain: 'studyhub-a667b.firebaseapp.com',
    storageBucket: 'studyhub-a667b.firebasestorage.app',
    measurementId: 'G-FDSLVMZXWM',
  );
}
